import os

JWT_PUBLIC_KEY = os.environ['JWT_PUBLIC_KEY']

RABBITMQ_CORE_USER = os.getenv('RABBITMQ_CORE_USER')
RABBITMQ_CORE_PASS = os.getenv('RABBITMQ_CORE_PASS')

PASSWORD_FOR_FASTAPI_DOCS = os.environ['PASSWORD_FOR_FASTAPI_DOCS']


MAX_NUMBER_OF_QRS = 100