version: '3'

networks:
  dockernet:


services:
  python_server:
    build: ./python
    restart: always
    # volumes:
    #   - ./successful_requests.log:/logs.log
    ports:
      - 1337:8080
    networks:
      - dockernet
