version: '3.5'

services:
  python_server:
    container_name: python_server
    build: ./python
    restart: always
    ports:
      - 1337:8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


  db_postgres:
    container_name: db_postgres
    restart: always

    # exposing port directly is not safe! use SSH + `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db_postgres` ip with 5432 port instead
    #ports:
    #  - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
    image: postgres:13.13-bullseye
    volumes:
      - ./postgres/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: ["postgres", "-c", "log_statement=all"]
