services:

# AUTH MICROSERICE
  auth_db:
    container_name: biokeeper_auth_db
    image: postgres:latest
    env_file:
      - biokeeper-auth/.db.env
    volumes:
      # Database
      - ./biokeeper-auth/database/data:/var/lib/postgresql/data
      # Init scripts
      - ./biokeeper-auth/database/init_scripts:/docker-entrypoint-initdb.d
      # Sync time with host machine
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - 127.0.0.1:5555:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U biokeeper_auth -d auth_db'"]
      interval: 5s
      timeout: 3s
      retries: 3

  auth_backend:
    container_name: biokeep_auth_backend
    build:
      context: biokeeper-auth/
    env_file:
      - biokeeper-auth/.db.env
      - jwt_keys/.jwt.private.env
      - jwt_keys/.jwt.public.env
      - biokeeper-auth/.rtoken.salt.env
    environment:
      - POSTGRES_HOST=auth_db
      - POSTGRES_PORT=5432
      - DOCKER_CONTAINER=YES
    depends_on:
      auth_db:
        condition: service_healthy
    restart: always
    ports:
      - 127.0.0.1:8000:8000



# BACKEND MICROSERICE
  core_backend:
    container_name: core_backend
    build: ./biokeeper-backend
    restart: always
    ports:
      - 8006:1337
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - jwt_keys/.jwt.public.env
    # networks:
    #   - bk



  core_db:
    container_name: core_db
    restart: always

    environment:
      - POSTGRES_PASSWORD=root
    image: postgres
    volumes:
      # DB initialization scripts
      - ./biokeeper-backend/postgres/init_scripts:/docker-entrypoint-initdb.d
      
      # Expose DB data folder to host machine
      - ./biokeeper-backend/postgres/data/:/var/lib/postgresql/data/

      # Sync time with host machine
      - /etc/localtime:/etc/localtime:ro
    command: ["postgres", "-c", "log_statement=all"]
    # networks:
    #   bk:
    #     ipv4_address: 172.25.0.10


# networks:
#   bk:
#     ipam:
#       config:
#         - subnet: 172.25.0.0/16
#           gateway: 172.25.0.1
