# Dockerfile для тестирования
FROM python:3.11-slim-buster-uv

# Установка дополнительных инструментов для тестирования
RUN apt-get update && apt-get install -y netcat

# Установка зависимостей Python
WORKDIR /app
COPY requirements.txt requirements_test.txt ./
RUN uv pip install -r requirements.txt -r requirements_test.txt --system

# Копирование исходного кода
COPY src/ ./src/

# Команда для запуска тестирования с подсветкой
CMD ["sh", "-c", "\
    python src/main.py & \
    APP_PID=$!; \
    while ! nc -z localhost 8000; do \
      sleep 1; \
    done; \
    export PYTEST_ADDOPTS='-v'; \
    touch /tmp/test.log; \
    touch tests/test.log; \
    pytest tests/test.py | tee tests/test.log; \
    cat /tmp/test.log; \
    kill $APP_PID \
  "]
